/**
 * Hand-curated word packs — every word a team can be dealt, by category and
 * difficulty. These replaced live LLM word generation (July 2026) so that
 * every word shown to a classroom or family is vetted in advance, games cost
 * nothing to run, and word delivery can never fail or stall.
 *
 * Curation rules (yourkids.com content guardrails):
 *  - Suitable for a classroom: nothing rude, violent beyond storybook level,
 *    partisan, or brand-heavy; no living politicians.
 *  - Describable: a partner must be able to clue it without saying it.
 *  - British English spellings; internationally recognisable where possible.
 *  - easy ≈ a 6–8-year-old knows it; medium ≈ upper primary / general
 *    knowledge; hard ≈ abstract, technical or adult-level.
 *  - At least 20 unique words per list (enforced by lib/words.test.js).
 *
 * Words are stored in display case and uppercased on serve. Keep each list
 * alphabetised-by-vibe (roughly thematic) rather than strictly — it makes
 * review easier than alphabetical order does.
 */

export const WORD_PACKS = {
  'General': {
    easy: [
      'APPLE', 'UMBRELLA', 'RAINBOW', 'BICYCLE', 'SANDCASTLE', 'TOOTHBRUSH',
      'PILLOW', 'PUDDLE', 'BALLOON', 'LADDER', 'POSTMAN', 'SCISSORS',
      'BIRTHDAY CAKE', 'WELLIES', 'SNOWMAN', 'PLAYGROUND', 'KETTLE',
      'BLANKET', 'TREEHOUSE', 'PIRATE', 'ROBOT', 'PANCAKE',
    ],
    medium: [
      'LIGHTHOUSE', 'ORCHESTRA', 'AVALANCHE', 'PASSPORT', 'SKELETON',
      'TELESCOPE', 'WHIRLPOOL', 'COMPASS', 'MARATHON', 'JIGSAW',
      'THUNDERSTORM', 'SUBMARINE', 'SCARECROW', 'FINGERPRINT', 'GREENHOUSE',
      'WATERFALL', 'CARNIVAL', 'DRAGONFLY', 'ECHO', 'QUICKSAND', 'HAMMOCK',
      'ORIGAMI',
    ],
    hard: [
      'DEJA VU', 'NOSTALGIA', 'PROCRASTINATION', 'MIRAGE', 'SARCASM',
      'CLAUSTROPHOBIA', 'COINCIDENCE', 'SILHOUETTE', 'ULTIMATUM', 'PARADOX',
      'WILLPOWER', 'RUMOUR', 'TRADITION', 'METAPHOR', 'CURIOSITY',
      'DEADLINE', 'HORIZON', 'INTUITION', 'ETIQUETTE', 'AMBITION',
      'GRAPEVINE', 'SMALL TALK',
    ],
  },

  'Animals': {
    easy: [
      'DOG', 'ELEPHANT', 'PENGUIN', 'BUTTERFLY', 'KANGAROO', 'GIRAFFE',
      'OCTOPUS', 'HEDGEHOG', 'LADYBIRD', 'TORTOISE', 'DOLPHIN', 'OWL',
      'SPIDER', 'CROCODILE', 'SQUIRREL', 'PARROT', 'RABBIT', 'SNAIL',
      'TIGER', 'DUCK', 'MONKEY', 'POLAR BEAR',
    ],
    medium: [
      'CHAMELEON', 'FLAMINGO', 'PORCUPINE', 'JELLYFISH', 'WOODPECKER',
      'ORANGUTAN', 'SEAHORSE', 'MEERKAT', 'PELICAN', 'BADGER', 'PUFFIN',
      'LOBSTER', 'GAZELLE', 'STICK INSECT', 'KILLER WHALE', 'TARANTULA',
      'MOLE', 'HERON', 'NEWT', 'OTTER', 'WALRUS', 'HAMSTER',
    ],
    hard: [
      'AXOLOTL', 'NARWHAL', 'PANGOLIN', 'CAPYBARA', 'ECHIDNA', 'TAPIR',
      'LEMMING', 'IBEX', 'CUTTLEFISH', 'MANTIS SHRIMP', 'KOMODO DRAGON',
      'PLATYPUS', 'ARMADILLO', 'CHINCHILLA', 'MONGOOSE', 'SALAMANDER',
      'ANTEATER', 'SLOW WORM', 'OSPREY', 'STOAT', 'WOMBAT', 'PUFFERFISH',
    ],
  },

  'Science': {
    easy: [
      'MAGNET', 'VOLCANO', 'THERMOMETER', 'BATTERY', 'MICROSCOPE',
      'LIGHTNING', 'BUBBLE', 'SHADOW', 'MELTING', 'FREEZING', 'PLANET',
      'SEED', 'HEART', 'LUNGS', 'MAGNIFYING GLASS', 'STEAM', 'ROCKET',
      'DINOSAUR', 'FLOATING', 'X-RAY', 'BRAIN', 'ROBOT ARM',
    ],
    medium: [
      'GRAVITY', 'FRICTION', 'EVAPORATION', 'PHOTOSYNTHESIS', 'CIRCUIT',
      'ATOM', 'FOSSIL', 'ORBIT', 'VACCINE', 'MICROBE', 'CONDENSATION',
      'ECOSYSTEM', 'PREDATOR', 'HABITAT', 'MOLECULE', 'ENERGY',
      'REFLECTION', 'DIGESTION', 'POLLINATION', 'LABORATORY',
      'MAGNETIC FIELD', 'PERISCOPE',
    ],
    hard: [
      'QUANTUM', 'ENZYME', 'CHROMOSOME', 'CATALYST', 'INERTIA', 'ISOTOPE',
      'NEURON', 'RADIATION', 'HYPOTHESIS', 'EVOLUTION', 'CENTRIFUGE',
      'ELECTRON', 'OSMOSIS', 'PHOTON', 'VELOCITY', 'ANTIBODY',
      'PERIODIC TABLE', 'EQUILIBRIUM', 'MUTATION', 'TURBINE', 'ALGORITHM',
      'LASER',
    ],
  },

  'Geography': {
    easy: [
      'MOUNTAIN', 'RIVER', 'ISLAND', 'BEACH', 'DESERT', 'MAP', 'FOREST',
      'LAKE', 'BRIDGE', 'CASTLE', 'CITY', 'FARM', 'WAVE', 'CAVE', 'VILLAGE',
      'OCEAN', 'HILL', 'FLAG', 'JUNGLE', 'IGLOO', 'NORTH POLE', 'CLIFF',
    ],
    medium: [
      'PENINSULA', 'GLACIER', 'CANYON', 'EQUATOR', 'CONTINENT', 'DELTA',
      'HARBOUR', 'PLATEAU', 'VALLEY', 'MARSH', 'REEF', 'DUNE', 'AMAZON',
      'SAHARA', 'EVEREST', 'NILE', 'ICELAND', 'VENICE',
      'GREAT BARRIER REEF', 'STONEHENGE', 'CAPITAL CITY', 'BORDER',
    ],
    hard: [
      'ARCHIPELAGO', 'TRIBUTARY', 'ISTHMUS', 'SAVANNAH', 'PERMAFROST',
      'LATITUDE', 'MERIDIAN', 'EROSION', 'ESTUARY', 'ATOLL', 'STRAIT',
      'MONSOON', 'GEYSER', 'FAULT LINE', 'CARTOGRAPHER', 'ALTITUDE',
      'HEMISPHERE', 'OASIS', 'TIMBUKTU', 'KILIMANJARO', 'PATAGONIA',
      'TUNDRA',
    ],
  },

  'History': {
    easy: [
      'KING', 'QUEEN', 'KNIGHT', 'CROWN', 'PYRAMID', 'MUMMY', 'SWORD',
      'SHIELD', 'VIKING', 'TREASURE', 'SCROLL', 'ARMOUR', 'CHARIOT',
      'THRONE', 'DUNGEON', 'CANNON', 'CAVEMAN', 'SAILING SHIP',
      'DRAWBRIDGE', 'GLADIATOR', 'TORCH', 'CROWN JEWELS',
    ],
    medium: [
      'PHARAOH', 'EMPIRE', 'REVOLUTION', 'PLAGUE', 'MEDIEVAL', 'SAMURAI',
      'AQUEDUCT', 'COLOSSEUM', 'STONE AGE', 'ARCHAEOLOGIST', 'MONARCHY',
      'EXPLORER', 'TELEGRAPH', 'STEAM ENGINE', 'ROMAN EMPIRE',
      'GREAT WALL OF CHINA', 'TITANIC', 'ANGLO-SAXON', 'GUNPOWDER',
      'SUFFRAGETTE', 'TIME CAPSULE', 'CASTLE MOAT',
    ],
    hard: [
      'RENAISSANCE', 'ABDICATION', 'ARMISTICE', 'FEUDALISM', 'DYNASTY',
      'PROPAGANDA', 'ALCHEMY', 'MAGNA CARTA', 'HIEROGLYPHICS',
      'INDUSTRIAL REVOLUTION', 'CIVILISATION', 'ARTEFACT', 'CHRONOLOGY',
      'EXCAVATION', 'MERCENARY', 'TREATY', 'REPUBLIC', 'CENSUS', 'SIEGE',
      'PILGRIM', 'ORACLE', 'BARTER',
    ],
  },

  'Space': {
    easy: [
      'MOON', 'SUN', 'STAR', 'ROCKET SHIP', 'ALIEN', 'PLANET', 'ASTRONAUT',
      'EARTH', 'TELESCOPE', 'COMET', 'MARS', 'SATURN', 'SHOOTING STAR',
      'SPACE SUIT', 'CRATER', 'COUNTDOWN', 'JUPITER', 'SPACE STATION',
      'MILKY WAY', 'UFO', 'MOON LANDING', 'STARGAZING',
    ],
    medium: [
      'GALAXY', 'SATELLITE', 'METEOR', 'ECLIPSE', 'ASTEROID',
      'CONSTELLATION', 'SOLAR SYSTEM', 'NORTH STAR', 'ZERO GRAVITY',
      'MISSION CONTROL', 'OBSERVATORY', 'LIGHT YEAR', 'ROVER', 'VENUS',
      'MERCURY', 'NEPTUNE', 'SPACE WALK', 'ROCKET FUEL', 'ORBIT',
      'BIG BANG', 'LUNAR ECLIPSE', 'TELESCOPE MIRROR',
    ],
    hard: [
      'BLACK HOLE', 'SUPERNOVA', 'NEBULA', 'WORMHOLE', 'EVENT HORIZON',
      'EXOPLANET', 'RED GIANT', 'WHITE DWARF', 'ASTEROID BELT',
      'COSMIC RAY', 'DARK MATTER', 'INTERSTELLAR', 'TERRAFORMING',
      'PULSAR', 'QUASAR', 'HELIOCENTRIC', 'SPACE-TIME', 'ESCAPE VELOCITY',
      'VACUUM', 'PAYLOAD', 'RE-ENTRY', 'ANTIMATTER',
    ],
  },

  'Books & Stories': {
    easy: [
      'FAIRY TALE', 'DRAGON', 'WIZARD', 'PRINCESS', 'GIANT', 'MERMAID',
      'LIBRARY', 'BOOKMARK', 'ONCE UPON A TIME', 'BIG BAD WOLF',
      'GLASS SLIPPER', 'MAGIC WAND', 'TREASURE MAP', 'GOLDILOCKS',
      'CINDERELLA', 'PICTURE BOOK', 'BEDTIME STORY', 'GENIE', 'UNICORN',
      'WITCH', 'THREE LITTLE PIGS', 'MAGIC CARPET',
    ],
    medium: [
      'AUTHOR', 'CHAPTER', 'VILLAIN', 'PLOT TWIST', 'SEQUEL', 'NARRATOR',
      'FABLE', 'LEGEND', 'MYTH', 'POETRY', 'RHYME', 'NOVEL', 'ILLUSTRATOR',
      'ROBIN HOOD', 'KING ARTHUR', 'EXCALIBUR', 'PETER PAN',
      'ALICE IN WONDERLAND', 'SHERLOCK HOLMES', 'TROLL',
      'HAPPILY EVER AFTER', 'CLIFFHANGER',
    ],
    hard: [
      'PROTAGONIST', 'ANTHOLOGY', 'AUTOBIOGRAPHY', 'FORESHADOWING',
      'ALLITERATION', 'MANUSCRIPT', 'PSEUDONYM', 'SATIRE', 'TRILOGY',
      'EPILOGUE', 'LIMERICK', 'ONOMATOPOEIA', 'PLOT HOLE', 'RED HERRING',
      'UNRELIABLE NARRATOR', 'FIRST EDITION', 'HAIKU', 'FOLKLORE',
      'GENRE', 'PARCHMENT', 'PAGE-TURNER', 'POETIC LICENCE',
    ],
  },

  'Sport & Games': {
    easy: [
      'FOOTBALL', 'GOAL', 'SWIMMING', 'RACE', 'MEDAL', 'TROPHY',
      'HOPSCOTCH', 'HIDE AND SEEK', 'SKIPPING ROPE', 'TRAMPOLINE',
      'WHISTLE', 'CRICKET', 'TENNIS', 'SLEDGE', 'GOALKEEPER',
      'MUSICAL CHAIRS', 'SNAKES AND LADDERS', 'FINISH LINE', 'REFEREE',
      'BULLSEYE', 'TUG OF WAR', 'SOMERSAULT',
    ],
    medium: [
      'MARATHON RUNNER', 'PENALTY', 'HAT-TRICK', 'GYMNASTICS', 'ARCHERY',
      'BADMINTON', 'ROUNDERS', 'NETBALL', 'CHESS', 'DOMINOES', 'CHARADES',
      'RELAY', 'JAVELIN', 'HURDLES', 'TABLE TENNIS', 'SNOOKER',
      'DARTBOARD', 'STOPWATCH', 'WEMBLEY', 'OLYMPICS', 'LEAGUE TABLE',
      'HALF-TIME',
    ],
    hard: [
      'DECATHLON', 'CHECKMATE', 'PHOTO FINISH', 'UNDERDOG', 'GRANDMASTER',
      'BIATHLON', 'DRESSAGE', 'STALEMATE', 'GAMBIT', 'SUDDEN DEATH',
      'HOME ADVANTAGE', 'PERSONAL BEST', 'SPORTSMANSHIP', 'SLAM DUNK',
      'HOLE IN ONE', 'OFFSIDE', 'TIEBREAK', 'POLE VAULT', 'TRIPLE JUMP',
      'PARALYMPICS', 'QUALIFIER', 'FALSE START',
    ],
  },

  'Food': {
    easy: [
      'PIZZA', 'BANANA', 'ICE CREAM', 'SANDWICH', 'CARROT', 'SPAGHETTI',
      'CHEESE', 'BISCUIT', 'PORRIDGE', 'JELLY', 'TOAST', 'STRAWBERRY',
      'CUPCAKE', 'FISH AND CHIPS', 'POPCORN', 'HONEY', 'YOGHURT',
      'BROCCOLI', 'WATERMELON', 'LEMONADE', 'SAUSAGE ROLL', 'BAKED BEANS',
    ],
    medium: [
      'RECIPE', 'INGREDIENTS', 'AVOCADO', 'CROISSANT', 'LASAGNE',
      'OMELETTE', 'MARMALADE', 'CHOPSTICKS', 'BARBECUE', 'CASSEROLE',
      'HUMMUS', 'MANGO', 'COCONUT', 'PRETZEL', 'WAFFLE', 'CURRY',
      'NOODLES', 'PICNIC', 'BAKERY', 'VEGETARIAN', 'ROAST DINNER',
      'MARKET STALL',
    ],
    hard: [
      'FERMENTATION', 'UMAMI', 'SOUFFLE', 'MERINGUE', 'SOURDOUGH',
      'PASTEURISED', 'CARAMELISE', 'GLUTEN', 'MARINADE', 'GARNISH',
      'DELICACY', 'MICHELIN STAR', 'FOOD MILES', 'KNEADING', 'BRIOCHE',
      'RATATOUILLE', 'WASABI', 'TURMERIC', 'VINAIGRETTE', 'AL DENTE',
      'ZEST', 'SEASONING',
    ],
  },

  'Music': {
    easy: [
      'DRUM', 'GUITAR', 'PIANO', 'SINGER', 'TRUMPET', 'VIOLIN', 'CHOIR',
      'DANCING', 'CLAPPING', 'MICROPHONE', 'NURSERY RHYME', 'LULLABY',
      'BAND', 'CONCERT', 'RECORDER', 'TAMBOURINE', 'XYLOPHONE',
      'HEADPHONES', 'KARAOKE', 'TRIANGLE', 'POP STAR', 'HUMMING',
    ],
    medium: [
      'MELODY', 'RHYTHM', 'HARMONY', 'CONDUCTOR', 'SAXOPHONE', 'CELLO',
      'BAGPIPES', 'UKULELE', 'DUET', 'SOLO', 'ENCORE', 'CHORUS',
      'ACCORDION', 'HARMONICA', 'BRASS BAND', 'SHEET MUSIC', 'BEETHOVEN',
      'MOZART', 'OPERA', 'JAZZ', 'FESTIVAL', 'EARWORM',
    ],
    hard: [
      'CRESCENDO', 'A CAPPELLA', 'SYMPHONY', 'FALSETTO', 'IMPROVISATION',
      'METRONOME', 'OCTAVE', 'PERFECT PITCH', 'SOPRANO', 'VIBRATO',
      'SYNCOPATION', 'CONCERTO', 'PHILHARMONIC', 'TEMPO', 'TREBLE CLEF',
      'AMPLIFIER', 'ACOUSTIC', 'BARITONE', 'LYRICIST', 'OVERTURE',
      'STAGE FRIGHT', 'BUSKER',
    ],
  },

  'Nature & Outdoors': {
    easy: [
      'TREE', 'FLOWER', 'RAIN', 'SNOW', 'LEAF', 'MUSHROOM', 'ACORN',
      'NEST', 'POND', 'GARDEN', 'WORM', 'CATERPILLAR', 'SUNFLOWER',
      'PEBBLE', 'CAMPFIRE', 'TENT', 'ROOTS', 'BLOSSOM', 'CONKER', 'DAISY',
      'RAINDROP', 'MUD PIE',
    ],
    medium: [
      'HIBERNATION', 'COMPOST', 'ORCHARD', 'MEADOW', 'BRAMBLE',
      'TOADSTOOL', 'TADPOLE', 'MIGRATION', 'POLLEN', 'MOSS', 'FERN',
      'WILDFLOWER', 'BIRDWATCHING', 'HIKING', 'ROCKPOOL', 'DEN', 'WILLOW',
      'HEDGEROW', 'FROST', 'RIVERBANK', 'HARVEST', 'DEW',
    ],
    hard: [
      'METAMORPHOSIS', 'CHLOROPHYLL', 'UNDERGROWTH', 'CANOPY',
      'BIODIVERSITY', 'POLLINATOR', 'DECIDUOUS', 'FUNGUS', 'LICHEN',
      'SAPLING', 'CHRYSALIS', 'NOCTURNAL', 'CAMOUFLAGE', 'PETRICHOR',
      'WILDERNESS', 'CONSERVATION', 'REWILDING', 'BRACKEN', 'SPORE',
      'EVERGREEN', 'BURROW', 'THICKET',
    ],
  },

  'Christmas': {
    easy: [
      'SANTA', 'REINDEER', 'PRESENT', 'STOCKING', 'SNOWMAN', 'TINSEL',
      'CHRISTMAS TREE', 'ELF', 'SLEIGH', 'CAROL', 'CRACKER', 'ANGEL',
      'TURKEY', 'MINCE PIE', 'ADVENT CALENDAR', 'FAIRY LIGHTS',
      'WRAPPING PAPER', 'CHIMNEY', 'RUDOLPH', 'SNOWBALL', 'GINGERBREAD',
      'MISTLETOE',
    ],
    medium: [
      'NUTCRACKER', 'YULE LOG', 'NATIVITY', 'SCROOGE', 'PANTOMIME',
      'BAUBLE', 'WREATH', 'CANDY CANE', 'JINGLE BELLS', 'SECRET SANTA',
      'BOXING DAY', 'WINTER SOLSTICE', 'SNOW GLOBE', 'ICICLE',
      'NEW YEAR\'S EVE', 'BRUSSELS SPROUTS', 'CHRISTMAS EVE', 'GROTTO',
      'SILENT NIGHT', 'EGGNOG', 'TOBOGGAN', 'LAPLAND',
    ],
    hard: [
      'WASSAILING', 'GOODWILL', 'HUMBUG', 'TIDINGS', 'FIGGY PUDDING',
      'THREE WISE MEN', 'MYRRH', 'FRANKINCENSE', 'POINSETTIA', 'SUGARPLUM',
      'CHESTNUTS', 'ADVENT', 'ORNAMENT', 'FESTIVITIES', 'GENEROSITY',
      'MIDWINTER', 'PERFECT GIFT', 'THANK-YOU LETTER', 'FAMILY TRADITION',
      'CAROL SERVICE', 'GIFT TAG', 'DECK THE HALLS',
    ],
  },

  'Shakespeare': {
    easy: [
      'STAGE', 'ACTOR', 'CROWN', 'GHOST', 'WITCH', 'SWORD FIGHT',
      'THEATRE', 'MASK', 'POTION', 'POET', 'BALCONY', 'FOOL', 'QUILL',
      'COSTUME', 'APPLAUSE', 'CURTAIN', 'VILLAIN', 'STORM', 'SHIPWRECK',
      'DONKEY', 'FAIRY', 'DUEL',
    ],
    medium: [
      'ROMEO AND JULIET', 'HAMLET', 'MACBETH', 'GLOBE THEATRE', 'SONNET',
      'PUCK', 'A MIDSUMMER NIGHT\'S DREAM', 'THE TEMPEST',
      'STRATFORD-UPON-AVON', 'ELIZABETHAN', 'TO BE OR NOT TO BE',
      'PLAYWRIGHT', 'COMEDY', 'TRAGEDY', 'STAGE DIRECTIONS', 'UNDERSTUDY',
      'VERONA', 'THREE WITCHES', 'LADY MACBETH', 'OBERON', 'YORICK',
      'CROWN PRINCE',
    ],
    hard: [
      'SOLILOQUY', 'IAMBIC PENTAMETER', 'FORSOOTH', 'BODKIN', 'WHEREFORE',
      'MONTAGUE', 'CAPULET', 'TWELFTH NIGHT', 'FALSTAFF', 'IAGO',
      'KING LEAR', 'OTHELLO', 'THE SCOTTISH PLAY', 'STAR-CROSSED',
      'QUARTO', 'GROUNDLINGS', 'ASIDE', 'BLANK VERSE',
      'MUCH ADO ABOUT NOTHING', 'CORDELIA', 'ET TU BRUTE', 'EXEUNT',
    ],
  },
};

/** Category names, in the order the setup screen shows them. */
export const GENRES = Object.keys(WORD_PACKS);
